### ISSUE TITLE
[BUG] Missing subtitle text on pet spells

### ISSUE THREAD

**Issue by JamminL** [JamminL/cata-classic-bugs#909]
#### 1.1. Description
Pet spells have a subtext, some are missing currently.
  #### 1.2. How to Reproduce
           1. Call your Hunter pet
           2. Open Pet spell tab
           3. Notice how "Assist" for example, does not have sub text
  #### 1.3  Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/107503518/e8fb41ab-77dc-4180-b357-15cb4c1ba72f)
#### 2.1. Description
Spells in cata should all have subtext
  #### 2.2 Source Material
![image](https://github.com/JamminL/cata-classic-bugs/assets/107503518/5ab2c079-92d0-4626-a510-f1f784692da2)

**Comment by Artemishowl** [comment]
This should already be fixed.

**Comment by JamminL** [comment]
Very minor but Pet commands and passives are still missing the subtext as reported

**Comment by Artemishowl** [comment]
Will need more context, because I tested the following:
- Checked pet talents (learned and unlearned)
- Pets with unique abilities
- Basic pet commands and passives.

I think I need more details. Are you running addons? Are you on a different client that is non-English based maybe?

**Comment by Artemishowl** [comment]
EDIT: I thought this meant tooltips, I'm dummy. Updating.
