### ISSUE TITLE
[BUG] Shaman's Elemental Precision grants 3% flat Spell Hit Chance

### ISSUE THREAD

**Issue by raethkcj** [JamminL/cata-classic-bugs#981]
#### 1.1. Description
 Elemental Shaman's [Elemental Precision](https://www.wowhead.com/cata/spell=30674/elemental-precision) talent has an extra, erroneous effect on it that grants a flat 3% Spell Hit Chance *in addition* to converting Spirit to Spell Hit Rating. This hit chance only applies to the spells listed in the "Affected Spells" section shown on wowhead.
  #### 1.2. How to Reproduce
           1. Talent into Elemental Precision
           2. Equip Spirit and/or Hit Rating such that your total Spell Hit Chance is greater than 14% and less than 17%
           3. Record a large sample of Lightning Bolt casts vs a +3 enemy, such that you have a nonzero expected miss rate
           4. Observe that they do not miss
  #### 1.3  Source Material
  All of these tests were performed with a level 82 character attacking a level 85 Training Dummy.
Two encounters totaling 198+254 = 452 Lightning Bolt casts, performed with Elemental Precision talented and 2.47% expected Miss Chance, showing 0% observed Miss Chance (the secondary Lightning Bolt with several Misses is from Mastery: Elemental Overload, which is not affected by the bugged Elemental Precision effect)
https://www.warcraftlogs.com/reports/CwghZrdVz1jqbpJW#fight=last&type=damage-done&source=3
https://www.warcraftlogs.com/reports/XpyHvxGcAzrYa7df#fight=1&type=damage-done&source=3
![ElePrecisionOn](https://github.com/JamminL/cata-classic-bugs/assets/7716908/35bdaf8f-6e34-477a-b097-b548e49dc25c)

If we really had a 2.47% Miss Chance, the probability of seeing 0% Misses in 452 casts is `(1 - 0.0254) ^ 452 = 0.00089%`, making it exceedingly likely this is bugged.

One encounter totaling 247 Lightning Bolt casts, with Elemental Precision **NOT** talented, and 2.83% expected Miss Chance, showing 1.98% observed Miss Chance, which is a reasonable observation given the sample size.
https://www.warcraftlogs.com/reports/XpyHvxGcAzrYa7df#fight=2&type=damage-done&source=3
![ElePrecisionOff](https://github.com/JamminL/cata-classic-bugs/assets/7716908/71146e0d-9faa-407c-843b-dbcaaed33b44)

#### 2.1. Description
  Elemental Precision should not give any Spell Hit Chance beyond its conversion of Spirit to Spell Hit Rating.
  #### 2.2 Source Material
Tooltip

**Comment by Artemishowl** [comment]
This should be resolved as of 4/19

**Comment by raethkcj** [comment]
It's possible the fix is queued for tomorrow's build, but as of the current Beta, the issue is still present under the same test conditions:
https://www.warcraftlogs.com/reports/AyPV4nqC2L3DNa6r#fight=last&type=damage-done&source=4

**Comment by raethkcj** [comment]
Retested May 29th with 2.7% expected miss chance and again got no misses on Lightning Bolt:
![image](https://github.com/JamminL/cata-classic-bugs/assets/7716908/ce19dc4a-df79-4e65-b1c1-8f431e35131f)
https://www.warcraftlogs.com/reports/jCtq4NKahdBX7xDb#fight=last&type=damage-done&source=1

Specifically, I believe this row in the database is not intended to exist in Cataclysm, and is providing the extra hit:
https://wago.tools/db2/SpellEffect?branch=wow_classic&filter[ID]=848715&page=1

**Comment by raethkcj** [comment]
https://us.forums.blizzard.com/en/wow/t/cataclysm-classic-hotfixes-june-3/1843458/241
